import { StateGraph, START, END, StateSchema, type GraphNode, type CompiledStateGraph } from "@langchain/langgraph";
import z from "zod";
import { mistralModel, cohereModel, geminiModel } from "./model.ai.js";
import { createAgent, providerStrategy /*for gemini*/, toolStrategy /*for other models*/ } from "langchain";
import { HumanMessage } from "langchain";


/*
StateSchema => Defines the structure of the state in the graph, including properties and their types.
Nodes jo data aapas me exchange karte hain toh uss data ka format kya hoga, uske liye StateSchema define karte hain.
 */

const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })

})

const solutionNode: GraphNode<typeof state> = async (state) => {

    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ])

    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state;

    /**
     * judge response = {
     * solution_1_score:7,
     * solution_2_score:3,
     * solution_1_reasoning: "reasoning for sol 1",
     * solution_2_reasoning: "reasoning for sol 2"
     * }
    */

    const judge = createAgent({
        model: geminiModel,
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().int().min(0).max(10),
            solution_2_score: z.number().int().min(0).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string(),
        })),
        systemPrompt: `You are a judge tasked with evaluationg two solutions generated by different AI models. Please provide a score out of 10 for each solution along with your reasoning for the scores.`
    })

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the solutions and provide scores and reasoning.
                `)
        ]
    })

    const { solution_1_score, solution_2_score, solution_1_reasoning, solution_2_reasoning } = judgeResponse.structuredResponse;

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }
}

const graph = new StateGraph(state)
    .addNode("solutionNode", solutionNode)
    .addNode("judgeNode", judgeNode)
    .addEdge(START, "solutionNode")
    .addEdge("solutionNode", "judgeNode")
    .addEdge("judgeNode", END)
    .compile()

    export  default async function (problem: string) {
        const result = await graph.invoke({
            problem: problem
        })

        return result
    }
